### ISSUE TITLE
add an option to delete imported pdf/files

### ISSUE THREAD

**Issue by thperret** [openpaperwork/paperwork#567]
there could be an option in parameters to automatically remove files that have been successfully imported into paperwork.

Use case:
Very often, I import some pdf files and forget to remove them from my downloads folder then when I clean the downloads folder I need to check each files to be sure it was imported into paperwork.

**Comment by jflesch** [comment]
There is a feature already existing that may interest you:
When importing, just indicate to Paperwork the folder where you store your PDF:
* it will look recursively for PDF files
* it will automatically import those not yet imported, and ignore those already imported.

**Comment by jflesch** [comment]
(currently, if you target one PDF specifically, it will always be imported. This behavior will be changed in 1.1.0)

**Comment by thperret** [comment]
oh nice ! I didn't know that.
Thanks

**Comment by MathieuSchopfer** [comment]
I think this could be implemented quite easily by turning the `Gtk.MessageDialog()` information window of method `ActionImport.__import_ok()` into a question dialogue box and catching its `response` signal in a function that would, when requested, delete the imported files.

This, also, wouldn't be any extra effort for the user, since they already have to click the  _Validate_ button of the import summary dialogue window.

**Comment by jflesch** [comment]
Implemented in 1.2
