### ISSUE TITLE
Samba (and other network protocols) support?

### ISSUE THREAD

**Issue by kri5** [openpaperwork/paperwork#625]
Is there any plans to support Samba shares? And Other protocols maybe?
Many people now have a NAS or equivalent, and it would be convenient to be able to 
manipulate file directly on theses shares.

**Comment by jflesch** [comment]
If you mount the remote directory as a drive, it should work : https://openpaper.work/bin/paperwork_doc/sharing_network_folder_en_0007.png

**Comment by jflesch** [comment]
But yeah, at some point, it will have to be fully supported

**Comment by kri5** [comment]
This way of mounting it as a drive would prevent to use it properly from different computer, or you would have to have the same mount points in all the computers (laptop, desktop, etc..)

This adds more room for user mistakes.

**Comment by kri5** [comment]
Btw why did you tag this issue as windows only?

**Comment by jflesch** [comment]
Yeah, I guess it's pretty much the same problem on Linux. Gnome GVFS should be used.
However, that will makes it harder to port to Android I guess.

**Comment by tYYGH** [comment]
I don’t really understand what the problem is…

I already use Paperwork off the network. My papers are stored on an NFS mount point. And I already have 2 computers (a desktop and a laptop) reading these papers (in addition to my web viewer). Each computer maintains its own ~/… cache folder, and updates it when starting.

I don’t use Windows, but I’m pretty sure that mounting papers on E:\ on one computer and on H:\ on another computer is not a problem, as long as each computer has its own cache folder, and uses always the same letter.

**Comment by jflesch** [comment]
On GNU/Linux:
Gnome uses GIO : If the user accessed remote servers using Gnome/Nautilus, and you want your application to access them too, you can't use the usual file API (```open()```, ```close()```, etc). You have to use ```Gio.File()``` objects.
Right now, Paperwork-backend is using the standard ```open()/close()```, so it can only access files on non-Gnome mount points. But as you saw, it works fine if you use standard mount points.

On Windows:
If I'm not mistaken, even the standard open()/close() functions can access remote servers (```open("\\\\remoteserver\\sharing\\file.txt", "r")``` should work directly.
The problem is in the file chooser dialogs : Because of the way things work on GNU/Linux, they are created with ```local_only=True```. So they don't display remote servers, unless they are mounted as a drive.

**Comment by jflesch** [comment]
Basically, the best solution here would be to simply use GIo (previously gvfs) everywhere, and set ```local_only``` to ```False``` on every file choose dialog.

**Comment by jflesch** [comment]
Done:
https://github.com/openpaperwork/paperwork-backend/commit/0bfe489a4997e15cc6e91c4030beace93d8403b5
https://github.com/openpaperwork/paperwork/commit/a7c955cdfcf52eaeded26fe0028042430ff44e35
https://github.com/openpaperwork/paperwork-backend/commit/244a3fe617b6e042d115ec997cb0a467a5af8394
https://github.com/openpaperwork/paperwork/commit/8d1221ff5284345eba6d627ef15292becf1f5d14

Will require a lot of testing

**Comment by jflesch** [comment]
Actually, part of the problem is Windows specific: For some reason, GtkFileChooser dialogs on Windows never display remote locations.

**Comment by jflesch** [comment]
Nevermind, bad test from my part.
