### ISSUE TITLE
after installing tesseract setting not longer open

### ISSUE THREAD

**Issue by icf20** [openpaperwork/paperwork#756]
installed papaerwork via AUR and **then installed** tesseract now the setting diagonal not longer opens

advanced work but not settings, any idea why ?

**Comment by jflesch** [comment]
Did you mean the `settings dialog` ?

Since you installed Paperwork using AUR, you should report this kind of bug first to the maintainer (who would then report it back to me if required).

Anyway, whether you installed Tesseract or Paperwork first is probably unrelated to your problem.
Can you try to open the settings dialog (which will fail), then obtain [the diagnostic output please](https://github.com/openpaperwork/paperwork/wiki/Getting-the-diagnostic-output) ?

**Comment by icf20** [comment]
> Did you mean the settings dialog ?

this

![image](https://user-images.githubusercontent.com/17784575/37003506-8c8b5e3e-20cd-11e8-8eed-cb196757f649.png)



```
INFO   paperwork.frontend.settingswindow Distribution: [arch]
ERROR  paperwork.frontend.settingswindow Unable to load languages translations
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paperwork/frontend/settingswindow/__init__.py", line 804, in __init__
    'iso639-3', pycountry.LOCALES_DIR
  File "/usr/lib/python3.6/gettext.py", line 514, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso639-3'
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paperwork/frontend/util/actions.py", line 97, in on_action_activated_cb
    return self.__do()
  File "/usr/lib/python3.6/site-packages/paperwork/frontend/util/actions.py", line 64, in __do
    return self.do(**kwargs)
  File "/usr/lib/python3.6/site-packages/paperwork/frontend/mainwindow/__init__.py", line 1373, in do
    self.__main_win.window, self.__config)
  File "/usr/lib/python3.6/site-packages/paperwork/frontend/settingswindow/__init__.py", line 816, in __init__
    short_ocr_langs = ocr_tools[0].get_available_languages()
  File "/usr/lib/python3.6/site-packages/pyocr/tesseract.py", line 406, in get_available_languages
    raise TesseractError(ret, "unable to get languages")
pyocr.error.TesseractError: (1, 'unable to get languages')
ERROR  paperwork.frontend.diag        ===========================
INFO   paperwork.frontend.mainwindow.pages No box selected
INFO   paperwork.frontend.mainwindow.pages [page] found 0 boxes to highlight
```

**Comment by jflesch** [comment]
What happens when you try to run Tesseract from a terminal ?
Have you installed training files for your languages ? Note that in any case, you must also install the training file for English (don't ask me why, but Tesseract always needs it)

**Comment by icf20** [comment]
> Have you installed training files for your language(s) ? 

i did only spanish

>  Note that in any case, you must also install the training file for English (don't ask me why, but Tesseract always needs it)

BINGO! after installing that the settings open

**Comment by jflesch** [comment]
Yeah, you should report that the AUR maintainer. It's a missing dependency and you're not the first one to have that problem :/

**Comment by icf20** [comment]
done, @StreakyCobra

**Comment by jflesch** [comment]
I meant the AUR maintainer of Tesseract, not Paperwork. (sorry I should have specified)

**Comment by icf20** [comment]
> I meant the AUR maintainer of Tesseract

https://www.archlinux.org/packages/community/x86_64/tesseract/ package on community look like all language file are optional

**Comment by jflesch** [comment]
That's my point. English is not.

**Comment by StreakyCobra** [comment]
Hi,

I don't know about the dependency problem between `tesseract-data-eng` and `tesseract`, but if this is not solved, or not a problem of the `tesseract` package, I can still add it as a dependency to `paperwork` later.

**Comment by jflesch** [comment]
@StreakyCobra From what I understand, it's more of a bug in Tesseract 3. It looks for the English training file to know if any training data is installed. If it is not, it assumes none is installed and return an error. I wouldn't be surprised if it's already fixed in Tesseract 4.
While I assume it's a bug, not having the English training file makes Tesseract useless. So it makes sense to add it as a mandatory dependency for Tesseract 3. This is what the Debian packager has done: https://packages.debian.org/fr/wheezy/tesseract-ocr

**Comment by StreakyCobra** [comment]
I see, thanks for the info. If they don't fix it in `tesseract` directly I'll fix it in paperwork at least.
